[2025-05-03 16:45:08,790: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 16:45:08,803: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-03 16:45:08,803: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 16:45:08,807: INFO/MainProcess] mingle: searching for neighbors
[2025-05-03 16:45:09,431: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 16:45:09,442: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-03 16:45:09,443: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 16:45:09,444: INFO/MainProcess] mingle: searching for neighbors
[2025-05-03 16:45:09,814: INFO/MainProcess] mingle: all alone
[2025-05-03 16:45:09,823: INFO/MainProcess] short1@d433d9014655 ready.
[2025-05-03 16:45:10,454: INFO/MainProcess] mingle: all alone
[2025-05-03 16:45:10,478: INFO/MainProcess] short2@d433d9014655 ready.
[2025-05-03 16:46:23,095: INFO/MainProcess] Task djcelery_email_send_multiple[82dad089-6be9-4321-875a-4ab32526104a] received
[2025-05-03 16:46:23,097: INFO/MainProcess] Task djcelery_email_send_multiple[2f0b9733-2baf-4ab5-97f7-9619407b6852] received
[2025-05-03 16:46:23,398: ERROR/ForkPoolWorker-6] djcelery_email_send_multiple[82dad089-6be9-4321-875a-4ab32526104a]: Cannot reach CELERY_EMAIL_BACKEND django.core.mail.backends.smtp.EmailBackend
Traceback (most recent call last):
  File "/home/mediacms.io/lib/python3.13/site-packages/djcelery_email/tasks.py", line 40, in send_emails
    conn.open()
    ~~~~~~~~~^^
  File "/home/mediacms.io/lib/python3.13/site-packages/django/core/mail/backends/smtp.py", line 86, in open
    self.connection = self.connection_class(
                      ~~~~~~~~~~~~~~~~~~~~~^
        self.host, self.port, **connection_params
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
                                    self.source_address)
                                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/socket.py", line 864, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.13/socket.py", line 849, in create_connection
    sock.connect(sa)
    ~~~~~~~~~~~~^^^^
ConnectionRefusedError: [Errno 111] Connection refused
[2025-05-03 16:46:23,399: ERROR/ForkPoolWorker-6] djcelery_email_send_multiple[2f0b9733-2baf-4ab5-97f7-9619407b6852]: Cannot reach CELERY_EMAIL_BACKEND django.core.mail.backends.smtp.EmailBackend
Traceback (most recent call last):
  File "/home/mediacms.io/lib/python3.13/site-packages/djcelery_email/tasks.py", line 40, in send_emails
    conn.open()
    ~~~~~~~~~^^
  File "/home/mediacms.io/lib/python3.13/site-packages/django/core/mail/backends/smtp.py", line 86, in open
    self.connection = self.connection_class(
                      ~~~~~~~~~~~~~~~~~~~~~^
        self.host, self.port, **connection_params
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
                                    self.source_address)
                                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/socket.py", line 864, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.13/socket.py", line 849, in create_connection
    sock.connect(sa)
    ~~~~~~~~~~~~^^^^
ConnectionRefusedError: [Errno 111] Connection refused
[2025-05-03 16:46:23,644: WARNING/ForkPoolWorker-6] djcelery_email_send_multiple[82dad089-6be9-4321-875a-4ab32526104a]: Failed to send email message to ['info@mediacms.io'], retrying. (ConnectionRefusedError(111, 'Connection refused'))
[2025-05-03 16:46:23,644: WARNING/ForkPoolWorker-6] djcelery_email_send_multiple[2f0b9733-2baf-4ab5-97f7-9619407b6852]: Failed to send email message to ['xjsunny@gmail.com'], retrying. (ConnectionRefusedError(111, 'Connection refused'))
[2025-05-03 16:46:23,660: INFO/ForkPoolWorker-6] Task djcelery_email_send_multiple[82dad089-6be9-4321-875a-4ab32526104a] succeeded in 0.5613899170002696s: 0
[2025-05-03 16:46:23,662: INFO/MainProcess] Task djcelery_email_send_multiple[82dad089-6be9-4321-875a-4ab32526104a] received
[2025-05-03 16:46:23,674: INFO/ForkPoolWorker-6] Task djcelery_email_send_multiple[2f0b9733-2baf-4ab5-97f7-9619407b6852] succeeded in 0.5739966669998466s: 0
[2025-05-03 16:46:23,675: INFO/MainProcess] Task djcelery_email_send_multiple[2f0b9733-2baf-4ab5-97f7-9619407b6852] received
[2025-05-03 16:46:39,244: INFO/MainProcess] Task save_user_action[0fe9713d-b501-4f1b-8929-8f88edacbea4] received
[2025-05-03 16:46:39,365: INFO/ForkPoolWorker-6] Task save_user_action[0fe9713d-b501-4f1b-8929-8f88edacbea4] succeeded in 0.1171252080002887s: True
[2025-05-03 16:49:23,940: ERROR/ForkPoolWorker-6] djcelery_email_send_multiple[2f0b9733-2baf-4ab5-97f7-9619407b6852]: Cannot reach CELERY_EMAIL_BACKEND django.core.mail.backends.smtp.EmailBackend
Traceback (most recent call last):
  File "/home/mediacms.io/lib/python3.13/site-packages/djcelery_email/tasks.py", line 40, in send_emails
    conn.open()
    ~~~~~~~~~^^
  File "/home/mediacms.io/lib/python3.13/site-packages/django/core/mail/backends/smtp.py", line 86, in open
    self.connection = self.connection_class(
                      ~~~~~~~~~~~~~~~~~~~~~^
        self.host, self.port, **connection_params
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
                                    self.source_address)
                                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/socket.py", line 864, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.13/socket.py", line 849, in create_connection
    sock.connect(sa)
    ~~~~~~~~~~~~^^^^
ConnectionRefusedError: [Errno 111] Connection refused
[2025-05-03 16:49:23,940: ERROR/ForkPoolWorker-6] djcelery_email_send_multiple[82dad089-6be9-4321-875a-4ab32526104a]: Cannot reach CELERY_EMAIL_BACKEND django.core.mail.backends.smtp.EmailBackend
Traceback (most recent call last):
  File "/home/mediacms.io/lib/python3.13/site-packages/djcelery_email/tasks.py", line 40, in send_emails
    conn.open()
    ~~~~~~~~~^^
  File "/home/mediacms.io/lib/python3.13/site-packages/django/core/mail/backends/smtp.py", line 86, in open
    self.connection = self.connection_class(
                      ~~~~~~~~~~~~~~~~~~~~~^
        self.host, self.port, **connection_params
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
                                    self.source_address)
                                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/socket.py", line 864, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.13/socket.py", line 849, in create_connection
    sock.connect(sa)
    ~~~~~~~~~~~~^^^^
ConnectionRefusedError: [Errno 111] Connection refused
[2025-05-03 16:49:24,250: WARNING/ForkPoolWorker-6] djcelery_email_send_multiple[82dad089-6be9-4321-875a-4ab32526104a]: Failed to send email message to ['info@mediacms.io'], retrying. (ConnectionRefusedError(111, 'Connection refused'))
[2025-05-03 16:49:24,250: WARNING/ForkPoolWorker-6] djcelery_email_send_multiple[2f0b9733-2baf-4ab5-97f7-9619407b6852]: Failed to send email message to ['xjsunny@gmail.com'], retrying. (ConnectionRefusedError(111, 'Connection refused'))
[2025-05-03 16:49:24,258: INFO/ForkPoolWorker-6] Task djcelery_email_send_multiple[2f0b9733-2baf-4ab5-97f7-9619407b6852] succeeded in 0.6013241669998024s: 0
[2025-05-03 16:49:24,258: INFO/ForkPoolWorker-6] Task djcelery_email_send_multiple[82dad089-6be9-4321-875a-4ab32526104a] succeeded in 0.6003089579999141s: 0
[2025-05-03 16:49:24,260: INFO/MainProcess] Task djcelery_email_send_multiple[82dad089-6be9-4321-875a-4ab32526104a] received
[2025-05-03 16:49:24,260: INFO/MainProcess] Task djcelery_email_send_multiple[2f0b9733-2baf-4ab5-97f7-9619407b6852] received
[2025-05-03 16:52:24,576: ERROR/ForkPoolWorker-6] djcelery_email_send_multiple[82dad089-6be9-4321-875a-4ab32526104a]: Cannot reach CELERY_EMAIL_BACKEND django.core.mail.backends.smtp.EmailBackend
Traceback (most recent call last):
  File "/home/mediacms.io/lib/python3.13/site-packages/djcelery_email/tasks.py", line 40, in send_emails
    conn.open()
    ~~~~~~~~~^^
  File "/home/mediacms.io/lib/python3.13/site-packages/django/core/mail/backends/smtp.py", line 86, in open
    self.connection = self.connection_class(
                      ~~~~~~~~~~~~~~~~~~~~~^
        self.host, self.port, **connection_params
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
                                    self.source_address)
                                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/socket.py", line 864, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.13/socket.py", line 849, in create_connection
    sock.connect(sa)
    ~~~~~~~~~~~~^^^^
ConnectionRefusedError: [Errno 111] Connection refused
[2025-05-03 16:52:24,576: ERROR/ForkPoolWorker-6] djcelery_email_send_multiple[2f0b9733-2baf-4ab5-97f7-9619407b6852]: Cannot reach CELERY_EMAIL_BACKEND django.core.mail.backends.smtp.EmailBackend
Traceback (most recent call last):
  File "/home/mediacms.io/lib/python3.13/site-packages/djcelery_email/tasks.py", line 40, in send_emails
    conn.open()
    ~~~~~~~~~^^
  File "/home/mediacms.io/lib/python3.13/site-packages/django/core/mail/backends/smtp.py", line 86, in open
    self.connection = self.connection_class(
                      ~~~~~~~~~~~~~~~~~~~~~^
        self.host, self.port, **connection_params
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
                                    self.source_address)
                                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/socket.py", line 864, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.13/socket.py", line 849, in create_connection
    sock.connect(sa)
    ~~~~~~~~~~~~^^^^
ConnectionRefusedError: [Errno 111] Connection refused
[2025-05-03 16:52:24,884: WARNING/ForkPoolWorker-6] djcelery_email_send_multiple[82dad089-6be9-4321-875a-4ab32526104a]: Failed to send email message to ['info@mediacms.io'], retrying. (ConnectionRefusedError(111, 'Connection refused'))
[2025-05-03 16:52:24,884: WARNING/ForkPoolWorker-6] djcelery_email_send_multiple[2f0b9733-2baf-4ab5-97f7-9619407b6852]: Failed to send email message to ['xjsunny@gmail.com'], retrying. (ConnectionRefusedError(111, 'Connection refused'))
[2025-05-03 16:52:24,891: INFO/ForkPoolWorker-6] Task djcelery_email_send_multiple[82dad089-6be9-4321-875a-4ab32526104a] succeeded in 0.6280440000000453s: 0
[2025-05-03 16:52:24,891: INFO/ForkPoolWorker-6] Task djcelery_email_send_multiple[2f0b9733-2baf-4ab5-97f7-9619407b6852] succeeded in 0.6303022080001028s: 0
[2025-05-03 16:52:24,893: INFO/MainProcess] Task djcelery_email_send_multiple[2f0b9733-2baf-4ab5-97f7-9619407b6852] received
[2025-05-03 16:52:24,893: INFO/MainProcess] Task djcelery_email_send_multiple[82dad089-6be9-4321-875a-4ab32526104a] received
[2025-05-03 16:55:25,202: ERROR/ForkPoolWorker-6] djcelery_email_send_multiple[2f0b9733-2baf-4ab5-97f7-9619407b6852]: Cannot reach CELERY_EMAIL_BACKEND django.core.mail.backends.smtp.EmailBackend
Traceback (most recent call last):
  File "/home/mediacms.io/lib/python3.13/site-packages/djcelery_email/tasks.py", line 40, in send_emails
    conn.open()
    ~~~~~~~~~^^
  File "/home/mediacms.io/lib/python3.13/site-packages/django/core/mail/backends/smtp.py", line 86, in open
    self.connection = self.connection_class(
                      ~~~~~~~~~~~~~~~~~~~~~^
        self.host, self.port, **connection_params
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
                                    self.source_address)
                                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/socket.py", line 864, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.13/socket.py", line 849, in create_connection
    sock.connect(sa)
    ~~~~~~~~~~~~^^^^
ConnectionRefusedError: [Errno 111] Connection refused
[2025-05-03 16:55:25,202: ERROR/ForkPoolWorker-6] djcelery_email_send_multiple[82dad089-6be9-4321-875a-4ab32526104a]: Cannot reach CELERY_EMAIL_BACKEND django.core.mail.backends.smtp.EmailBackend
Traceback (most recent call last):
  File "/home/mediacms.io/lib/python3.13/site-packages/djcelery_email/tasks.py", line 40, in send_emails
    conn.open()
    ~~~~~~~~~^^
  File "/home/mediacms.io/lib/python3.13/site-packages/django/core/mail/backends/smtp.py", line 86, in open
    self.connection = self.connection_class(
                      ~~~~~~~~~~~~~~~~~~~~~^
        self.host, self.port, **connection_params
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
                                    self.source_address)
                                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/socket.py", line 864, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.13/socket.py", line 849, in create_connection
    sock.connect(sa)
    ~~~~~~~~~~~~^^^^
ConnectionRefusedError: [Errno 111] Connection refused
[2025-05-03 16:55:25,510: WARNING/ForkPoolWorker-6] djcelery_email_send_multiple[2f0b9733-2baf-4ab5-97f7-9619407b6852]: Failed to send email message to ['xjsunny@gmail.com'], retrying. (ConnectionRefusedError(111, 'Connection refused'))
[2025-05-03 16:55:25,510: WARNING/ForkPoolWorker-6] djcelery_email_send_multiple[82dad089-6be9-4321-875a-4ab32526104a]: Failed to send email message to ['info@mediacms.io'], retrying. (ConnectionRefusedError(111, 'Connection refused'))
[2025-05-03 16:55:25,524: ERROR/ForkPoolWorker-6] Task djcelery_email_send_multiple[2f0b9733-2baf-4ab5-97f7-9619407b6852] raised unexpected: ConnectionRefusedError(111, 'Connection refused')
Traceback (most recent call last):
  File "/home/mediacms.io/lib/python3.13/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
                 ~~~^^^^^^^^^^^^^^^^^
  File "/home/mediacms.io/lib/python3.13/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
           ~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/mediacms.io/lib/python3.13/site-packages/djcelery_email/tasks.py", line 57, in send_emails
    send_emails.retry([[message], combined_kwargs], exc=e, throw=False)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mediacms.io/lib/python3.13/site-packages/celery/app/task.py", line 736, in retry
    raise_with_context(exc)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/mediacms.io/lib/python3.13/site-packages/djcelery_email/tasks.py", line 48, in send_emails
    sent = conn.send_messages([dict_to_email(message)])
  File "/home/mediacms.io/lib/python3.13/site-packages/django/core/mail/backends/smtp.py", line 128, in send_messages
    new_conn_created = self.open()
  File "/home/mediacms.io/lib/python3.13/site-packages/django/core/mail/backends/smtp.py", line 86, in open
    self.connection = self.connection_class(
                      ~~~~~~~~~~~~~~~~~~~~~^
        self.host, self.port, **connection_params
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
                                    self.source_address)
                                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/socket.py", line 864, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.13/socket.py", line 849, in create_connection
    sock.connect(sa)
    ~~~~~~~~~~~~^^^^
ConnectionRefusedError: [Errno 111] Connection refused
[2025-05-03 16:55:25,523: ERROR/ForkPoolWorker-6] Task djcelery_email_send_multiple[82dad089-6be9-4321-875a-4ab32526104a] raised unexpected: ConnectionRefusedError(111, 'Connection refused')
Traceback (most recent call last):
  File "/home/mediacms.io/lib/python3.13/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
                 ~~~^^^^^^^^^^^^^^^^^
  File "/home/mediacms.io/lib/python3.13/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
           ~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/mediacms.io/lib/python3.13/site-packages/djcelery_email/tasks.py", line 57, in send_emails
    send_emails.retry([[message], combined_kwargs], exc=e, throw=False)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mediacms.io/lib/python3.13/site-packages/celery/app/task.py", line 736, in retry
    raise_with_context(exc)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/mediacms.io/lib/python3.13/site-packages/djcelery_email/tasks.py", line 48, in send_emails
    sent = conn.send_messages([dict_to_email(message)])
  File "/home/mediacms.io/lib/python3.13/site-packages/django/core/mail/backends/smtp.py", line 128, in send_messages
    new_conn_created = self.open()
  File "/home/mediacms.io/lib/python3.13/site-packages/django/core/mail/backends/smtp.py", line 86, in open
    self.connection = self.connection_class(
                      ~~~~~~~~~~~~~~~~~~~~~^
        self.host, self.port, **connection_params
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
                                    self.source_address)
                                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/socket.py", line 864, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.13/socket.py", line 849, in create_connection
    sock.connect(sa)
    ~~~~~~~~~~~~^^^^
ConnectionRefusedError: [Errno 111] Connection refused
[2025-05-03 17:06:37,797: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:06:37,809: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-03 17:06:37,809: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:06:37,811: INFO/MainProcess] mingle: searching for neighbors
[2025-05-03 17:06:38,386: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:06:38,397: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-03 17:06:38,397: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:06:38,398: INFO/MainProcess] mingle: searching for neighbors
[2025-05-03 17:06:38,819: INFO/MainProcess] mingle: all alone
[2025-05-03 17:06:38,833: INFO/MainProcess] short1@9f63ad6f4351 ready.
[2025-05-03 17:06:39,411: INFO/MainProcess] mingle: all alone
[2025-05-03 17:06:39,432: INFO/MainProcess] short2@9f63ad6f4351 ready.
[2025-05-03 17:13:44,792: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:13:44,805: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-03 17:13:44,806: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:13:44,807: INFO/MainProcess] mingle: searching for neighbors
[2025-05-03 17:13:45,464: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:13:45,477: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-03 17:13:45,478: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:13:45,480: INFO/MainProcess] mingle: searching for neighbors
[2025-05-03 17:13:45,818: INFO/MainProcess] mingle: all alone
[2025-05-03 17:13:45,837: INFO/MainProcess] short1@0516f97a7186 ready.
[2025-05-03 17:13:46,492: INFO/MainProcess] mingle: all alone
[2025-05-03 17:13:46,505: INFO/MainProcess] short2@0516f97a7186 ready.
[2025-05-03 17:21:17,470: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:21:17,483: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-03 17:21:17,483: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:21:17,485: INFO/MainProcess] mingle: searching for neighbors
[2025-05-03 17:21:17,899: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:21:17,909: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-03 17:21:17,910: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:21:17,911: INFO/MainProcess] mingle: searching for neighbors
[2025-05-03 17:21:18,498: INFO/MainProcess] mingle: all alone
[2025-05-03 17:21:18,514: INFO/MainProcess] short1@09899a3533db ready.
[2025-05-03 17:21:18,920: INFO/MainProcess] mingle: all alone
[2025-05-03 17:21:18,938: INFO/MainProcess] short2@09899a3533db ready.
[2025-05-03 17:28:25,977: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:28:25,988: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-03 17:28:25,989: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:28:25,990: INFO/MainProcess] mingle: searching for neighbors
[2025-05-03 17:28:26,475: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:28:26,487: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-03 17:28:26,488: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:28:26,489: INFO/MainProcess] mingle: searching for neighbors
[2025-05-03 17:28:27,001: INFO/MainProcess] mingle: all alone
[2025-05-03 17:28:27,019: INFO/MainProcess] short1@160a2272ab73 ready.
[2025-05-03 17:28:27,500: INFO/MainProcess] mingle: all alone
[2025-05-03 17:28:27,524: INFO/MainProcess] short2@160a2272ab73 ready.
[2025-05-03 17:41:13,571: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:41:13,582: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-03 17:41:13,583: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:41:13,586: INFO/MainProcess] mingle: searching for neighbors
[2025-05-03 17:41:14,055: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:41:14,066: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-03 17:41:14,066: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:41:14,070: INFO/MainProcess] mingle: searching for neighbors
[2025-05-03 17:41:14,595: INFO/MainProcess] mingle: all alone
[2025-05-03 17:41:14,609: INFO/MainProcess] short1@e5daeb951864 ready.
[2025-05-03 17:41:15,077: INFO/MainProcess] mingle: all alone
[2025-05-03 17:41:15,089: INFO/MainProcess] short2@e5daeb951864 ready.
[2025-05-03 17:49:56,363: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:49:56,387: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-03 17:49:56,391: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:49:56,400: INFO/MainProcess] mingle: searching for neighbors
[2025-05-03 17:49:57,090: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:49:57,102: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-03 17:49:57,103: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:49:57,107: INFO/MainProcess] mingle: searching for neighbors
[2025-05-03 17:49:57,414: INFO/MainProcess] mingle: all alone
[2025-05-03 17:49:57,429: INFO/MainProcess] short1@b03970e47443 ready.
[2025-05-03 17:49:58,118: INFO/MainProcess] mingle: all alone
[2025-05-03 17:49:58,138: INFO/MainProcess] short2@b03970e47443 ready.
[2025-05-03 17:54:07,933: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:54:07,944: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-03 17:54:07,944: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:54:07,946: INFO/MainProcess] mingle: searching for neighbors
[2025-05-03 17:54:08,401: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:54:08,412: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-03 17:54:08,413: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 17:54:08,414: INFO/MainProcess] mingle: searching for neighbors
[2025-05-03 17:54:08,958: INFO/MainProcess] mingle: all alone
[2025-05-03 17:54:08,975: INFO/MainProcess] short1@356359bfccc3 ready.
[2025-05-03 17:54:09,424: INFO/MainProcess] mingle: all alone
[2025-05-03 17:54:09,452: INFO/MainProcess] short2@356359bfccc3 ready.
[2025-05-03 18:00:35,116: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 18:00:35,128: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-03 18:00:35,129: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 18:00:35,130: INFO/MainProcess] mingle: searching for neighbors
[2025-05-03 18:00:35,606: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 18:00:35,617: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-03 18:00:35,617: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 18:00:35,619: INFO/MainProcess] mingle: searching for neighbors
[2025-05-03 18:00:36,143: INFO/MainProcess] mingle: all alone
[2025-05-03 18:00:36,157: INFO/MainProcess] short1@cac39521097f ready.
[2025-05-03 18:00:36,628: INFO/MainProcess] mingle: all alone
[2025-05-03 18:00:36,644: INFO/MainProcess] short2@cac39521097f ready.
[2025-05-03 18:30:44,977: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 18:30:44,989: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-03 18:30:44,989: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 18:30:44,991: INFO/MainProcess] mingle: searching for neighbors
[2025-05-03 18:30:45,527: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 18:30:45,537: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-03 18:30:45,538: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 18:30:45,541: INFO/MainProcess] mingle: searching for neighbors
[2025-05-03 18:30:46,003: INFO/MainProcess] mingle: all alone
[2025-05-03 18:30:46,015: INFO/MainProcess] short1@086ef771ea9f ready.
[2025-05-03 18:30:46,554: INFO/MainProcess] mingle: all alone
[2025-05-03 18:30:46,574: INFO/MainProcess] short2@086ef771ea9f ready.
[2025-05-03 18:39:45,344: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 18:39:45,357: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-03 18:39:45,358: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 18:39:45,360: INFO/MainProcess] mingle: searching for neighbors
[2025-05-03 18:39:45,890: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 18:39:45,901: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-03 18:39:45,901: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-03 18:39:45,905: INFO/MainProcess] mingle: searching for neighbors
[2025-05-03 18:39:46,370: INFO/MainProcess] mingle: all alone
[2025-05-03 18:39:46,386: INFO/MainProcess] short1@92bef8e80105 ready.
[2025-05-03 18:39:46,912: INFO/MainProcess] mingle: all alone
[2025-05-03 18:39:46,922: INFO/MainProcess] short2@92bef8e80105 ready.
[2025-05-03 21:49:41,387: INFO/MainProcess] missed heartbeat from long1@92bef8e80105
[2025-05-03 21:49:41,388: INFO/MainProcess] missed heartbeat from short1@92bef8e80105
[2025-05-03 23:13:15,493: INFO/MainProcess] missed heartbeat from long1@92bef8e80105
[2025-05-03 23:13:15,494: INFO/MainProcess] missed heartbeat from short1@92bef8e80105
[2025-05-03 23:37:25,379: INFO/MainProcess] missed heartbeat from long1@92bef8e80105
[2025-05-03 23:37:25,380: INFO/MainProcess] missed heartbeat from short1@92bef8e80105
[2025-05-04 00:09:32,766: INFO/MainProcess] missed heartbeat from short1@92bef8e80105
[2025-05-04 00:09:32,768: INFO/MainProcess] missed heartbeat from long1@92bef8e80105
[2025-05-04 01:05:19,859: INFO/MainProcess] missed heartbeat from short1@92bef8e80105
[2025-05-04 01:05:19,860: INFO/MainProcess] missed heartbeat from long1@92bef8e80105
[2025-05-04 01:35:52,228: INFO/MainProcess] missed heartbeat from short1@92bef8e80105
[2025-05-04 01:35:52,229: INFO/MainProcess] missed heartbeat from long1@92bef8e80105
[2025-05-04 02:27:55,677: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 02:27:55,688: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-04 02:27:55,689: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 02:27:55,691: INFO/MainProcess] mingle: searching for neighbors
[2025-05-04 02:27:56,247: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 02:27:56,257: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-04 02:27:56,258: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 02:27:56,259: INFO/MainProcess] mingle: searching for neighbors
[2025-05-04 02:27:56,699: INFO/MainProcess] mingle: all alone
[2025-05-04 02:27:56,712: INFO/MainProcess] short1@7403b013f297 ready.
[2025-05-04 02:27:57,273: INFO/MainProcess] mingle: all alone
[2025-05-04 02:27:57,295: INFO/MainProcess] short2@7403b013f297 ready.
[2025-05-04 02:37:58,020: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 02:37:58,031: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-04 02:37:58,032: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 02:37:58,036: INFO/MainProcess] mingle: searching for neighbors
[2025-05-04 02:37:58,793: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 02:37:58,804: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-04 02:37:58,804: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 02:37:58,806: INFO/MainProcess] mingle: searching for neighbors
[2025-05-04 02:37:59,044: INFO/MainProcess] mingle: all alone
[2025-05-04 02:37:59,055: INFO/MainProcess] short1@e8510b056d9a ready.
[2025-05-04 02:37:59,814: INFO/MainProcess] mingle: all alone
[2025-05-04 02:37:59,831: INFO/MainProcess] short2@e8510b056d9a ready.
[2025-05-04 02:48:36,620: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 02:48:36,632: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-04 02:48:36,633: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 02:48:36,637: INFO/MainProcess] mingle: searching for neighbors
[2025-05-04 02:48:37,168: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 02:48:37,179: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-04 02:48:37,180: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 02:48:37,181: INFO/MainProcess] mingle: searching for neighbors
[2025-05-04 02:48:37,649: INFO/MainProcess] mingle: all alone
[2025-05-04 02:48:37,669: INFO/MainProcess] short1@6577d8d84443 ready.
[2025-05-04 02:48:38,191: INFO/MainProcess] mingle: all alone
[2025-05-04 02:48:38,213: INFO/MainProcess] short2@6577d8d84443 ready.
[2025-05-04 03:47:33,038: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 03:47:33,049: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-04 03:47:33,049: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 03:47:33,053: INFO/MainProcess] mingle: searching for neighbors
[2025-05-04 03:47:33,447: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 03:47:33,457: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-04 03:47:33,458: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 03:47:33,459: INFO/MainProcess] mingle: searching for neighbors
[2025-05-04 03:47:34,062: INFO/MainProcess] mingle: all alone
[2025-05-04 03:47:34,071: INFO/MainProcess] short1@c97f6426f645 ready.
[2025-05-04 03:47:34,473: INFO/MainProcess] mingle: all alone
[2025-05-04 03:47:34,496: INFO/MainProcess] short2@c97f6426f645 ready.
[2025-05-04 04:57:26,695: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 04:57:26,706: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-04 04:57:26,707: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 04:57:26,708: INFO/MainProcess] mingle: searching for neighbors
[2025-05-04 04:57:27,128: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 04:57:27,140: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-04 04:57:27,141: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 04:57:27,145: INFO/MainProcess] mingle: searching for neighbors
[2025-05-04 04:57:27,723: INFO/MainProcess] mingle: all alone
[2025-05-04 04:57:27,745: INFO/MainProcess] short1@8d901d9ca192 ready.
[2025-05-04 04:57:28,157: INFO/MainProcess] mingle: all alone
[2025-05-04 04:57:28,165: INFO/MainProcess] short2@8d901d9ca192 ready.
[2025-05-04 05:22:09,584: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 05:22:09,594: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-04 05:22:09,595: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 05:22:09,596: INFO/MainProcess] mingle: searching for neighbors
[2025-05-04 05:22:10,113: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 05:22:10,124: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-04 05:22:10,125: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 05:22:10,126: INFO/MainProcess] mingle: searching for neighbors
[2025-05-04 05:22:10,608: INFO/MainProcess] mingle: all alone
[2025-05-04 05:22:10,620: INFO/MainProcess] short1@ea48acee3ac8 ready.
[2025-05-04 05:22:11,137: INFO/MainProcess] mingle: all alone
[2025-05-04 05:22:11,159: INFO/MainProcess] short2@ea48acee3ac8 ready.
[2025-05-04 05:24:57,101: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 05:24:57,119: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-04 05:24:57,120: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 05:24:57,122: INFO/MainProcess] mingle: searching for neighbors
[2025-05-04 05:24:57,648: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 05:24:57,659: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-04 05:24:57,659: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 05:24:57,661: INFO/MainProcess] mingle: searching for neighbors
[2025-05-04 05:24:58,135: INFO/MainProcess] mingle: all alone
[2025-05-04 05:24:58,157: INFO/MainProcess] short1@7f90a4d4d8f0 ready.
[2025-05-04 05:24:58,667: INFO/MainProcess] mingle: all alone
[2025-05-04 05:24:58,681: INFO/MainProcess] short2@7f90a4d4d8f0 ready.
[2025-05-04 05:30:24,484: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 05:30:24,495: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-04 05:30:24,496: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 05:30:24,499: INFO/MainProcess] mingle: searching for neighbors
[2025-05-04 05:30:24,794: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 05:30:24,805: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-04 05:30:24,806: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 05:30:24,809: INFO/MainProcess] mingle: searching for neighbors
[2025-05-04 05:30:25,511: INFO/MainProcess] mingle: all alone
[2025-05-04 05:30:25,523: INFO/MainProcess] short1@99999b03c0f1 ready.
[2025-05-04 05:30:25,821: INFO/MainProcess] mingle: all alone
[2025-05-04 05:30:25,835: INFO/MainProcess] short2@99999b03c0f1 ready.
[2025-05-04 05:34:27,156: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 05:34:27,168: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-04 05:34:27,169: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 05:34:27,170: INFO/MainProcess] mingle: searching for neighbors
[2025-05-04 05:34:27,594: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 05:34:27,604: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-04 05:34:27,605: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 05:34:27,608: INFO/MainProcess] mingle: searching for neighbors
[2025-05-04 05:34:28,179: INFO/MainProcess] mingle: all alone
[2025-05-04 05:34:28,199: INFO/MainProcess] short1@cd7afaebbb0b ready.
[2025-05-04 05:34:28,616: INFO/MainProcess] mingle: all alone
[2025-05-04 05:34:28,626: INFO/MainProcess] short2@cd7afaebbb0b ready.
[2025-05-04 16:10:38,774: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 16:10:38,786: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-04 16:10:38,787: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 16:10:38,791: INFO/MainProcess] mingle: searching for neighbors
[2025-05-04 16:10:39,290: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 16:10:39,301: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-04 16:10:39,302: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 16:10:39,303: INFO/MainProcess] mingle: searching for neighbors
[2025-05-04 16:10:39,802: INFO/MainProcess] mingle: all alone
[2025-05-04 16:10:39,811: INFO/MainProcess] short1@372098fc2f64 ready.
[2025-05-04 16:10:40,314: INFO/MainProcess] mingle: all alone
[2025-05-04 16:10:40,325: INFO/MainProcess] short2@372098fc2f64 ready.
[2025-05-04 16:16:56,499: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 16:16:56,510: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-04 16:16:56,511: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 16:16:56,512: INFO/MainProcess] mingle: searching for neighbors
[2025-05-04 16:16:56,932: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 16:16:56,943: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-04 16:16:56,943: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-04 16:16:56,947: INFO/MainProcess] mingle: searching for neighbors
[2025-05-04 16:16:57,520: INFO/MainProcess] mingle: all alone
[2025-05-04 16:16:57,546: INFO/MainProcess] short1@9bcc8f119c40 ready.
[2025-05-04 16:16:57,959: INFO/MainProcess] mingle: all alone
[2025-05-04 16:16:57,990: INFO/MainProcess] short2@9bcc8f119c40 ready.
[2025-05-04 16:17:14,124: INFO/MainProcess] Task save_user_action[9121cab1-ffbc-4bfa-87c9-37cae82c9996] received
[2025-05-04 16:17:14,185: INFO/ForkPoolWorker-6] Task save_user_action[9121cab1-ffbc-4bfa-87c9-37cae82c9996] succeeded in 0.05676579099963419s: True
[2025-05-05 07:14:31,899: WARNING/MainProcess] Substantial drift from short2@9bcc8f119c40 may mean clocks are out of sync.  Current drift is 511 seconds.  [orig: 2025-05-05 07:14:31.899202 recv: 2025-05-05 07:06:00.949497]
[2025-05-05 07:14:31,901: WARNING/MainProcess] Substantial drift from long1@9bcc8f119c40 may mean clocks are out of sync.  Current drift is 511 seconds.  [orig: 2025-05-05 07:14:31.901384 recv: 2025-05-05 07:06:00.950986]
[2025-05-05 10:46:48,615: INFO/MainProcess] missed heartbeat from long1@9bcc8f119c40
[2025-05-05 10:46:48,615: INFO/MainProcess] missed heartbeat from short1@9bcc8f119c40
[2025-05-06 06:23:10,974: INFO/MainProcess] missed heartbeat from long1@9bcc8f119c40
[2025-05-06 06:23:10,978: INFO/MainProcess] missed heartbeat from short1@9bcc8f119c40
[2025-05-06 06:40:59,873: INFO/MainProcess] missed heartbeat from long1@9bcc8f119c40
[2025-05-06 06:40:59,874: INFO/MainProcess] missed heartbeat from short1@9bcc8f119c40
[2025-05-06 06:57:17,851: INFO/MainProcess] missed heartbeat from short1@9bcc8f119c40
[2025-05-06 06:57:17,853: INFO/MainProcess] missed heartbeat from long1@9bcc8f119c40
[2025-05-06 07:13:16,734: INFO/MainProcess] missed heartbeat from long1@9bcc8f119c40
[2025-05-06 07:13:16,735: INFO/MainProcess] missed heartbeat from short1@9bcc8f119c40
[2025-05-06 07:28:53,719: INFO/MainProcess] missed heartbeat from short1@9bcc8f119c40
[2025-05-06 07:28:53,720: INFO/MainProcess] missed heartbeat from long1@9bcc8f119c40
[2025-05-06 07:47:02,003: INFO/MainProcess] missed heartbeat from short2@9bcc8f119c40
[2025-05-06 07:47:02,004: INFO/MainProcess] missed heartbeat from long1@9bcc8f119c40
[2025-05-06 07:47:02,741: INFO/MainProcess] missed heartbeat from long1@9bcc8f119c40
[2025-05-06 07:47:02,742: INFO/MainProcess] missed heartbeat from short1@9bcc8f119c40
[2025-05-06 09:06:48,672: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-06 09:06:48,683: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-06 09:06:48,684: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-06 09:06:48,686: INFO/MainProcess] mingle: searching for neighbors
[2025-05-06 09:06:49,060: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-06 09:06:49,071: INFO/MainProcess] Connected to redis://redis:6379/1
[2025-05-06 09:06:49,072: WARNING/MainProcess] /home/mediacms.io/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-05-06 09:06:49,075: INFO/MainProcess] mingle: searching for neighbors
[2025-05-06 09:06:49,704: INFO/MainProcess] mingle: all alone
[2025-05-06 09:06:49,724: INFO/MainProcess] short1@efae30e90e0e ready.
[2025-05-06 09:06:50,082: INFO/MainProcess] mingle: all alone
[2025-05-06 09:06:50,095: INFO/MainProcess] short2@efae30e90e0e ready.
